#GPIO and Logging
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_MODE_IMMEDIATE=y
 
#Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y

# Homework requirement: Heartbeat period
CONFIG_APP_HEARTBEAT_PERIOD_MS=500

#LED Features
CONFIG_LED_SUBSYSTEM=y

# Optional: Enable RGB LED (set to 'n' for homework submission)
CONFIG_RGB_LED_ENABLE=y

# Advance LED settings(optional)
CONFIG_LED_ADVANCED=y
CONFIG_LED_ENABLE_DEBUGGING=y
